name: Publish

on:
  create:
    ref_type: tag
    master_branch: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@master
        with:
          ref: ${{ steps.get_tag_name.outputs.TAG_NAME }}
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
      - run: yarn test
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.old-version }} => ${{ steps.publish.version }}"